name: CPUID MVP Pipeline

# Trigger the workflow manually
on:
  workflow_dispatch:

jobs:
  install:
    runs-on: [self-hosted, windows]  # Specify a self-hosted Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Check out the repository to the runner

      - name: Print current working directory
        run: |
          echo "Current working directory:"
          pwd

    # cd "C:\Users\tommy\Desktop\workspace\cpuid_automation_mvp"

      - name: Change directory to cpuid_automation_mvp and run pnpm install
        run: |
          cd "C:\Users\tommy\Desktop\workspace\cpuid_automation_mvp"
          pnpm install
          echo "pnpm install @nzxt/cam-core@69.0.0"
          pnpm install @nzxt/cam-core@69.0.0
          echo "pnpm list @nzxt/cam-core"
          pnpm list @nzxt/cam-core
        shell: powershell  # Use PowerShell shell for Windows environment
    
      - name:  get cur temp
        run: |
          cd "C:\Users\tommy\Desktop\workspace\cpuid_automation_mvp"
          echo "Current working directory:"
          pwd
          echo "Getting temps"
          ts-node ./cpuid_helpers/validate_cpuid_cpu_temps.ts
        shell: powershell  # Use PowerShell shell for Windows environment

  test:
    runs-on: [self-hosted, windows]  # Specify a self-hosted Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Check out the repository to the runner

      - name: install new version of cam-core
        run: |
          cd "C:\Users\tommy\Desktop\workspace\cpuid_automation_mvp"
          echo "pnpm install @nzxt/cam-core@69.1.0"
          pnpm install @nzxt/cam-core@69.1.0
          echo "pnpm list @nzxt/cam-core"
          pnpm list @nzxt/cam-core
          ts-node ./cpuid_helpers/validate_cpuid_cpu_temps.ts
        shell: powershell