name: CPUID MVP Pipeline

# Trigger the workflow manually
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, windows]  # Specify a self-hosted Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Check out the repository to the runner

      - name: Print current working directory
        run: |
          echo "Current working directory:"
          pwd

    # cd "C:\Users\tommy\Desktop\workspace\cpuid_automation_mvp"

      - name: Change directory to cpuid_automation_mvp and run pnpm install
        run: |
          pnpm install
          echo "pnpm install @nzxt/cam-core@69.0.0"
          pnpm install @nzxt/cam-core@69.0.0
          echo "pnpm list @nzxt/cam-core"
          pnpm list @nzxt/cam-core
        shell: powershell  # Use PowerShell shell for Windows environment
    
      - name:  get cur temp cam-core@69.0.0
        run: |
          echo "Current working directory:"
          pwd
          echo "Getting temps"
          ts-node ./cpuid_helpers/get_cpu_avg_temp.ts
          echo "Print out ./cpuid_reading.json"
          (Get-Content -Path "./cpuid_reading.json" | ConvertFrom-Json) | Format-List
        shell: powershell  # Use PowerShell shell for Windows environment

      - name: install new version of cam-core@69.1.0
        run: | 
          if (Test-Path -Path "./cpuid_reading.json") {
              Remove-Item -Path "./cpuid_reading.json"
              Write-Host "File removed."
          } else {
              Write-Host "File does not exist."
          }
          echo "pnpm install @nzxt/cam-core@69.1.0"
          pnpm install @nzxt/cam-core@69.1.0
          echo "pnpm list @nzxt/cam-core"
          pnpm list @nzxt/cam-core
          ts-node ./cpuid_helpers/get_cpu_avg_temp.ts
        shell: powershell
      
      - name:  get cur temp of cam-core@69.1.0
        run: |
          echo "pwd"
          pwd
          ts-node ./cpuid_helpers/get_cpu_avg_temp.ts
          echo "Print out ./cpuid_reading.json"
          (Get-Content -Path "./cpuid_reading.json" | ConvertFrom-Json) | Format-List
        shell: powershell  # Use PowerShell shell for Windows environment
      
      - name: cross validate CPUID values
        run: |
          pnpm test-cpuid
        shell: powershell
